#
# Executes commands at the start of an interactive session.
#
# Authors:
#	Lavi Blumberg <lavifb@gmail.com>
#


# Run filed in .zshrc.d in order
# To disable spesific scripts, add .disable to their extension
for fn in $HOME/.zshrc.d/*.zsh ; do
  source "$fn"
done
